### ISSUE TITLE
L10n

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/nextcloud-moment#1]
This package needs translations. https://github.com/nextcloud/docker-ci/blob/master/translations/Dockerfile currently only supports php's gettext extraction but this apps uses a custom tool to generate the .pot file (run `npm run extract-l10n` to see). So we need npm and something that invokes the script.

**Comment by ChristophWurst** [comment]
cc @morrisjobke

**Comment by MorrisJobke** [comment]
The biggest problem is that Nextcloud l10n only support to load translations from app namespaces and this one is a JS library, where it doesn't know which app namespace it belongs to. Any ideas how to solve this? Same applies to nextcloud-vue: https://github.com/nextcloud/nextcloud-vue/issues/97 and https://github.com/juliushaertl/nextcloud-vue-collections/issues/120

cc @skjnldsv @juliushaertl

**Comment by ChristophWurst** [comment]
Yes, correct, that is a problem. Because we can also not load the l10n files async as then files might obtain a string before the translations have arrived.

**Comment by ChristophWurst** [comment]
I have to think about that.

**Comment by ChristophWurst** [comment]
> I have to think about that.

Research on the internet has not brought me to any useful information on how to handle translations in third party packages/libs, so I think it would be best to just let the apps provide them.

For Vue components the strings can be mandatory props. For other packages the apps would have to pass in translations via objects or function parameters.

For this package we could change the default export from an object to a factory function that takes the translation strings as object.

Apps can then use it similar to the way the Vuex store is imported, configured and re-exported within an app.

`moment.js`:
```js
import { getLocale } from 'nextcloud-l10n'
import { getMoment } from 'nextcloud-moment'

export default moment = getMoment(
    getLocale(),
    {
        secondsAgo: t('mail', 'seconds ago'),
    }
)
```

This module can be imported from any other module of the app.

Does that make sense?

**Comment by georgehrke** [comment]
> so I think it would be best to just let the apps provide them.

What app stores all the strings so transfex detects them? Core? 

> For Vue components the strings can be mandatory props. For other packages the apps would have to pass in translations via objects or function parameters.

But that means whenever a component adds a translatable string, we need to add that prop to every occurrence of that component our code, right?

**Comment by ChristophWurst** [comment]
> What app stores all the strings so transfex detects them? Core?

No, the individual apps. Which would result in a bit of duplication.

> But that means whenever a component adds a translatable string, we need to add that prop to every occurrence of that component our code, right?

Right, that it cumbersome.

These are two valid concerns. I'm open for alternatives. Ideas?

**Comment by juliushaertl** [comment]
Regarding the component translations, but maybe also suitable for moment - I was thinking if we could use dynamic webpack import to load the translations depending on the language asynchronously from within the components libraries. When they are loaded we just register them with OC.L10N.register and they become available later in the vue app.

In the nextcloud vue components we have something like:

```
const loadTranslations = async () => {
	const language = OC.getLanguage()
	return import(`./lang/${language}.json`).then((json) => {
		OC.L10N.register('vue-components', json)
		return Promise.resolve()
	})
```

The vue app could then just wait for the promise to resolve before we actually start the app:

```
import { loadTranslations } from 'nextcloud-vue'

loadTranslations().then(() => {
	// init your app here
})
```

Still a bit of a dirty approach, but this would help us to avoid duplication of translations all over the place.

**Comment by skjnldsv** [comment]
@juliushaertl could we not do that directly from the apps themselves?
Since we standardise (kind of) our webpack configs, we could easily add a dedicated rule to just dump the l10n files from any of our apps into the dist folder or something?

I would avoid a hack in core as we're trying to be independent from it, and it would just add more difficulties to maintain.

Another thing could be to have a specific `t` function that automatically take the name of the app it's on. But that would result in a lot of duplicate string in transifex. :/

**Comment by juliushaertl** [comment]
> Since we standardise (kind of) our webpack configs, we could easily add a dedicated rule to just dump the l10n files from any of our apps into the dist folder or something?

Yes, of course that could also work with in app translations. For vue apps we could utilize http://kazupon.github.io/vue-i18n/ for example then.

> Another thing could be to have a specific t function that automatically take the name of the app it's on. But that would result in a lot of duplicate string in transifex. :/

But that would only work for in app translations, not for ones pulled in from 3rd party libraries like nextcloud-vue

**Comment by ChristophWurst** [comment]
>  I was thinking if we could use dynamic webpack import to load the translations depending on the language asynchronously

The downside of async loading is that it's async :stuck_out_tongue: 

For the moment lib this means we have to "block" the usage of `moment` until the translations are fetched because the app might otherwise ask for a moment string before they are loaded. Which makes the APIs less convenient to work with if you have to await a promise all the time.

Another (probably very theoretical and unlikely) issue with calling `OC.L10N.register` then is that different versions of nc-vue might have different translations for the very same string and then overwrite each other's value. Of course the questions is if this is really an issue but I just wanted to bring it up.

The question with the internal, async loading of translations in the Vue components is **where** to do it. There is no central module that is loaded every time. Components are loaded individually.  So there must either be a kind of singleton that loads the translations once for every component or a lot of duplication.

**Comment by MorrisJobke** [comment]
> Another thing could be to have a specific `t` function that automatically take the name of the app it's on. But that would result in a lot of duplicate string in transifex. :/

Then we also need to find a way to extract the strings from the apps that use those dependencies ... not the hardest task, but definitely a confusing one for translators and the transifex sync job code.
