### ISSUE TITLE
Package broken?

### ISSUE THREAD

**Issue by jotoeri** [nextcloud/nextcloud-moment#308]
According to docs/Readme, NC-Moment should automatically load the locale. On forms, i just recognized, it does not (https://github.com/nextcloud/forms/issues/606).

- It seems like while moving to Github-Actions, the 'build'-test got lost (The test named build is the autoapprove-action)?
- Probably due to that, it didn't get recognized, that the package does not build anymore? Looks like some breaking webpack-changes got lost...?!

-> Seems to me like the package ist more or less completely broken currently...? 🤔

**Comment by ChristophWurst** [comment]
We use it in Mail without any issues.

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/mail/pull/3947 the hide modules is broken because of a webpack upgrade
