### ISSUE TITLE
.fromNow() not working

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/nextcloud-moment#31]
`moment().fromNow()` gives the following error:

```
moment.js:3383 Uncaught TypeError: Cannot read property 'humanize' of undefined
    at Moment.from (moment.js:3383)
    at Moment.fromNow (moment.js:3390)
    at <anonymous>:1:9`
```

**Comment by georgehrke** [comment]
Seems to be related to manipulation of locales?

**Comment by ChristophWurst** [comment]
Could it be related to the binding of `this`? What happens if you use `moment.bind(moment)().fromNow()`?

**Comment by ChristophWurst** [comment]
Interestingly, the tests pass for me: https://github.com/ChristophWurst/nextcloud-moment/blob/19e68a13a001db837777fa91e91dc4ff57ff2ccc/test/index.test.js#L12

**Comment by georgehrke** [comment]
> What happens if you use `moment.bind(moment)().fromNow()`?

Same result sadly :/

**Comment by georgehrke** [comment]
> Interestingly, the tests pass for me:

But are you generally able to reproduce the bug?

**Comment by ChristophWurst** [comment]
No, I was not. I expected the test code to throw the same error but it was fine. Could you try npm link'ing the latest master of this lib? Does that work?

**Comment by georgehrke** [comment]
Same result.

I did some more debugging and found out that for some reason, `moment.locale()` returns undefined for me. `getLocale()` from the `nextcloud-l10n` package returns `en_GB`. Setting it to a different locale doesn't change anything about  `moment.locale()` returning undefined.

In contrast, the moment that's being shipped in the Nextcloud server returns `en` on `moment.locale()`

```
return createDuration({to: this, from: time}).locale(this.locale()).humanize(!withoutSuffix);
```

This is the line where the error is thrown. Since `this.locale()` returns undefined, `createDuration().locale()` also returns undefined and hence you can't call `humanize` on it.

**Comment by georgehrke** [comment]
The one million question is now: Why does moment.locale return undefined?

If i inspect the moment object in the console, `_locale` is proper populated.

**Comment by georgehrke** [comment]
`moment.locale.bind(moment)()` also gives `undefined`

**Comment by georgehrke** [comment]
If i set the locale manually after import it works, so it seems to be somehow related to https://github.com/ChristophWurst/nextcloud-moment/blob/master/lib/index.ts#L8

**Comment by georgehrke** [comment]
I added a console statement [here](https://github.com/ChristophWurst/nextcloud-moment/blob/master/lib/index.ts#L8) and `getLocale()` returns `en_US`. Meaning it's getting the default value from `OC` and it's not using the `en` fallback.

**Comment by georgehrke** [comment]
For some reason, it likes `en-US`, but not `en_US`. 🤔 

```
> moment.locale('en_US')
undefined
> moment.locale()
undefined
> moment.locale('en-US')
"en"
> moment.locale()
"en"
```

Anyway, enough debugging for today.

**Comment by ChristophWurst** [comment]
Oh this is so weird. We use the exact same logic and data for `moment.locale` https://github.com/nextcloud/server/blob/b9bc2417e7a8dc81feb0abe20359bedaf864f790/core/src/init.js#L108

**Comment by ChristophWurst** [comment]
Found it! It's the logic that should convert `a few seconds ago` to `seconds ago`. As it doesn't currently work anyway I commented out these parts. v0.2.2 works again!
