### ISSUE TITLE
New nextcloud/moment release

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud-moment#497]
The last release (1.1.1) was two years ago and ships a quite outdated moment version (2.24.0). A new release would be appreciated, to e.g. fix https://github.com/nextcloud/tasks/issues/1938.
@ChristophWurst @skjnldsv

**Comment by raimund-schluessler** [comment]
@ChristophWurst Is there any timeline you could give? I would like to release the next version of Tasks and bumping nextcloud/moment would be a cheap fix for the mentioned issue.

**Comment by ChristophWurst** [comment]
Done :confetti_ball:
